### ISSUE TITLE
Running this codemod got rid of all of my @providesModule pragmas

### ISSUE THREAD

**Issue by mangogogos** [sibelius/codemod-RN24-to-RN25#13]
An example of a typical module in my codebase:

```
'use strict';

/*
 * @providesModule GenericToast
 */

import React, {
  Platform,
  NativeModules,
} from 'react-native';

...implementation
```

After running the codemod:

```
'use strict';

import React from 'react';
import { Platform, NativeModules } from 'react-native';

... implementation
```

Thankfully I only have about a dozen modules that implement this pragma but it was still not great!

**Comment by reergymerej** [comment]
Yikes.  There's probably a recast option to retain comments.

**Comment by sibelius** [comment]
@mangogogos this PR could help https://github.com/sibelius/codemod-RN24-to-RN25/pull/3

maybe @alinz could help

**Comment by reergymerej** [comment]
Looks like this works as long as `@providesModule` is at the top of the file.  That's where I've always seen it placed.  Anyone know if there's an official standard for it?  Either way, I suppose the codemod shouldn't bust comments whatever/where ever they are.

**Comment by reergymerej** [comment]
It looks like *any* comments between `import React` and a preceding expression are lost.  Comments throughout the rest of the source are untouched.
